name: gdg_devfest
description: An app tot support the GDG Hoverboard website.

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: 0.0.4
  firebase_auth: 0.2.0
  firebase_database: 0.0.12
  firebase_storage: 0.0.5
  fluro: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
