name: gdg_devfest
description: An app tot support the GDG Hoverboard website.

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: 0.2.2
  firebase_database: 0.3.4
  fluro: ^1.2.1
  rxdart: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
